name: Publish TechDocs

on:
  workflow_call:
    inputs:
      entity_namespace:
        required: false
        type: string
        default: default
      entity_kind:
        required: true
        type: string
      entity_name:
        required: true
        type: string

jobs:
  publish-techdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs and TechDocs CLI
        run: pip install mkdocs-techdocs-core==1.* && npm install -g @techdocs/cli

      - name: Generate docs
        run: techdocs-cli generate --no-docker --source-dir . --output-dir ./site

      - name: Publish to Azure Blob Storage
        run: |
          techdocs-cli publish \
            --publisher-type azureBlobStorage \
            --azureAccountName ${{ secrets.TECHDOCS_AZURE_ACCOUNT_NAME }} \
            --azureAccountKey ${{ secrets.TECHDOCS_AZURE_ACCOUNT_KEY }} \
            --storage-name ${{ secrets.TECHDOCS_AZURE_CONTAINER_NAME }} \
            --entity ${{ inputs.entity_namespace }}/${{ inputs.entity_kind }}/${{ inputs.entity_name }} \
            --directory ./site
